# Generated by Django 4.0.1 on 2022-01-19 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_alter_playlist_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'verbose_name_plural': 'playlists'},
        ),
        migrations.AddField(
            model_name='playlist',
            name='image',
            field=models.TextField(default='tbeanie.jpg'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='link',
            field=models.TextField(default='TunesBeanie Song Link'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=models.TextField(default='TunesBeanie Song List'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.TextField(default='tbeanie.jpg')),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('aboutme', models.TextField(default='TunesBeanie About Me')),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'profiles',
            },
        ),
    ]
